# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 14:51
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedGif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image_height', models.PositiveSmallIntegerField()),
                ('image_width', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to=core.models.animated_gif_path, width_field='image_width')),
                ('period', models.CharField(choices=[('3hourly', '3hourly'), ('daily', 'daily')], max_length=10)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='image_height', upload_to=core.models.snapshot_path, width_field='image_width'),
        ),
    ]
