# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 14:41
from __future__ import unicode_literals

import core.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161208_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='animatedgif',
            name='image_preview',
            field=versatileimagefield.fields.VersatileImageField(height_field='image_height', null=True, upload_to=core.models.animated_gif_path, width_field='image_width'),
        ),
    ]
