# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 15:09
from __future__ import unicode_literals

import core.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animatedgif_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatedgif',
            name='image_preview',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to=core.models.animated_gif_path),
        ),
    ]
